### ISSUE TITLE
Increase branch coverage _get_form

### ISSUE THREAD

**Issue by jenniferlindberg** [andnil5/scrapy#16]
To begin with, branch coverage is 98% for the function `form.py`. There is one `Missing` part of branch coverage for the function `_get_form`, the check if the function raises `ValueError` if `el` is `None`.

**Comment by majate** [comment]
According to my branch coverage data, we are also missing the branch 110&rightarrow;exit in this function. This should be covered if we create a test where the response body has a form element, `formname` is incorrect, `formid` is incorrect, `formxpath` is None and `formnumber` is None.

E.g:
```py
def test_get_form_no_match(self):
    # GROUP 12 ADDED TEST CASE
    response = _buildresponse(
        b"""<form action="post.php" method="POST">
        <input type="hidden" name="test" value="val1">
        </form>""",
        url="http://www.example.com/index.html")
    formname = "a"
    formid = 1
    formnumber = None
    formxpath = None
    self.assertIsNone(_get_form(response, formname, formid, formnumber, formxpath))
```  

I can add this test, but I will wait until #18 is closed.
