### ISSUE TITLE
Increase branch coverage

### ISSUE THREAD

**Issue by majate** [andnil5/scrapy#9]
Add in total 10 additional tests that target 
- `scrapy.http.request.form._get_inputs`,
- `scrapy.http.request.form._get_form`,
- `scrapy.http.request.form._get_clickable`,
- `scrapy.utils.curl.curl_to_request_kwargs` or
- `scrapy.utils.python.get_func_args`

that increase the current branch coverage of the functions.

*This issue should probably be split into multiple issues regarding the specific functions once we have figured out which functions need additional tests.*

**Comment by jenniferlindberg** [comment]
The test that is added for `get_func_args` enhances branch coverage of the file `python.py` from 66% to 67%.

**Comment by jenniferlindberg** [comment]
The test that is added for `_get_inputs` enhances branch coverage of the file `form.py` from 97% to 98%.
